### ISSUE TITLE
Is Installation section missing something?

### ISSUE THREAD

**Issue by nevyen** [auth0/angular2-jwt#287]
Hey guys, 

I followed your installation section at the readme and created a auth.module.ts with the provided code. How ever I now try to make create the AuthHttp at my constructor I get the following error: 

```
Unhandled Promise rejection: No provider for AuthHttp! ; Zone: angular ; Task: Promise.then ; Value: 
NoProviderError {__zone_symbol__error: Error: DI Error at NoProviderError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:704…, _nativeError: ZoneAwareError, keys: Array[1], injectors: Array[1], __zone_symbol__message: "No provider for AuthHttp!"…}
 Error: DI Error
    at NoProviderError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:7047:33)
    at NoProviderError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:30345:16)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/vendor.bundle.js:60413:16)
    at new NoProviderError (http://localhost:4200/vendor.bundle.js:60475:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/vendor.bundle.js:82405:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:82444:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor.bundle.js:82376:25)
    at ReflectiveInjector_.get (http://localhost:4200/vendor.bundle.js:82245:21)
    at AppModuleInjector.get (/AppModule/module.ngfactory.js:245:145)
    at AppModuleInjector.getInternal (/AppModule/module.ngfactory.js:340:61)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:4200/vendor.bundle.js:61348:44)
    at CompiledTemplate.proxyViewClass.AppView.injectorGet (http://localhost:4200/vendor.bundle.js:83180:45)
    at CompiledTemplate.proxyViewClass.DebugAppView.injectorGet (http://localhost:4200/vendor.bundle.js:83608:49)
    at ElementInjector.get (http://localhost:4200/vendor.bundle.js:82684:27)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor.bundle.js:82441:24)
```
So the question is what I am missing? And is this maybe missing at the Installation section too? 

Thanks in advance

**Comment by nevyen** [comment]
Okay after trying a bit where the problem could be, I remembered a posting where they mention that the order of imports could have impacts to your app. 

So first my imports looks like: 
```
@NgModule({
  declarations: [
    AppComponent,
    routedComponents
  ],
  imports: [
    routing,
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    DashboardModule,
    AuthenticationModule,
    JwtModule

  ],
  providers: [CommmunicationService],
  bootstrap: [AppComponent ]
})
```
where JwtModule is my auth.module.ts

now I changed it to: 
```
@NgModule({
  declarations: [
    AppComponent,
    routedComponents
  ],
  imports: [
    routing,
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    JwtModule,
    DashboardModule,
    AuthenticationModule

  ],
  providers: [CommmunicationService],
  bootstrap: [AppComponent ]
})
```
and everything works fine.
Maybe this should be mentioned at the readme.md if someone implemented angular2-jwt later.
