### ISSUE TITLE
Errors trying to integrate angular2-jwt (auth0) into node.js/angular2 app using Systemjs

### ISSUE THREAD

**Issue by kieranfraser** [auth0/angular2-jwt#38]
Hey,

So I've been tackling this for the past few days straight and still can't seem to make headway. I'm copying the angular2-jwt.js file from node_modules into the public/auth folder using gulp and then mapping it using Systemjs as follows: 

`map: {
            "angular2-jwt": "auth/angular2-jwt/angular2-jwt.js"
        }`

The angular-jwt.js file is being found as there is no 404, however it's throwing up this error with angular2.js. 

Any clues on where to go from here would be appreciated (I'm pretty new to node/angular development)

Stack Trace:
`EXCEPTION: The selector "app" did not match any elements
angular2.js:22823 EXCEPTION: The selector "app" did not match any elementsBrowserDomAdapter.logError @ angular2.js:22823BrowserDomAdapter.logGroup @ angular2.js:22834ExceptionHandler.call @ angular2.js:1163(anonymous function) @ angular2.js:12481NgZone._notifyOnError @ angular2.js:13405collection_1.StringMapWrapper.merge.onError @ angular2.js:13309run @ angular2-polyfills.js:141(anonymous function) @ angular2.js:13328zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243microtask @ angular2.js:13360run @ angular2-polyfills.js:138(anonymous function) @ angular2.js:13328zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2.js:22823 STACKTRACE:BrowserDomAdapter.logError @ angular2.js:22823ExceptionHandler.call @ angular2.js:1165(anonymous function) @ angular2.js:12481NgZone._notifyOnError @ angular2.js:13405collection_1.StringMapWrapper.merge.onError @ angular2.js:13309run @ angular2-polyfills.js:141(anonymous function) @ angular2.js:13328zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243microtask @ angular2.js:13360run @ angular2-polyfills.js:138(anonymous function) @ angular2.js:13328zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305
angular2.js:22823 Error: The selector "app" did not match any elements
    at new BaseException (http://localhost:3000/dist/lib/angular2.js:7104:21)
    at DomRenderer.selectRootElement (http://localhost:3000/dist/lib/angular2.js:13724:15)
    at HostViewFactory.viewFactory_HostApp0 [as viewFactory] (viewFactory_HostApp:72:18)
    at AppViewManager_.createRootHostView (http://localhost:3000/dist/lib/angular2.js:9226:34)
    at http://localhost:3000/dist/lib/angular2.js:12246:46
    at Zone.run (http://localhost:3000/dist/lib/angular2-polyfills.js:138:17)
    at Zone.run (http://localhost:3000/dist/lib/angular2.js:13328:32)
    at zoneBoundFn (http://localhost:3000/dist/lib/angular2-polyfills.js:111:19)
    at lib$es6$promise$$internal$$tryCatch (http://localhost:3000/dist/lib/angular2-polyfills.js:1511:16)
    at lib$es6$promise$$internal$$invokeCallback (http://localhost:3000/dist/lib/angular2-polyfills.js:1523:17)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:3000/dist/lib/angular2-polyfills.js:2195:26)
    at Zone.fork (http://localhost:3000/dist/lib/angular2-polyfills.js:2253:40)
    at Zone.bind (http://localhost:3000/dist/lib/angular2-polyfills.js:109:48)
    at bindArguments (http://localhost:3000/dist/lib/angular2-polyfills.js:980:29)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (http://localhost:3000/dist/lib/angular2-polyfills.js:1000:37)
    at DynamicComponentLoader_.loadAsRoot (http://localhost:3000/dist/lib/angular2.js:12245:49)
    at di_1.provide.useFactory (http://localhost:3000/dist/lib/angular2.js:12343:39)
    at Injector._instantiate (http://localhost:3000/dist/lib/angular2.js:11354:19)
    at Injector._instantiateProvider (http://localhost:3000/dist/lib/angular2.js:11287:21)
    at Injector._new (http://localhost:3000/dist/lib/angular2.js:11277:19)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (http://localhost:3000/dist/lib/angular2-polyfills.js:2195:26)
    at Zone.fork (http://localhost:3000/dist/lib/angular2-polyfills.js:2253:40)
    at NgZone._createInnerZone (http://localhost:3000/dist/lib/angular2.js:13316:39)
    at new NgZone (http://localhost:3000/dist/lib/angular2.js:13182:32)
    at createNgZone (http://localhost:3000/dist/lib/angular2.js:12365:12)
    at PlatformRef_.application (http://localhost:3000/dist/lib/angular2.js:12440:31)
    at Object.bootstrap (http://localhost:3000/dist/lib/angular2.js:24543:64)
    at execute (http://localhost:3000/dist/boot.js:113:23)
    at ensureEvaluated (http://localhost:3000/dist/lib/system.src.js:2981:26)
    at Object.execute (http://localhost:3000/dist/lib/system.src.js:3099:13)BrowserDomAdapter.logError @ angular2.js:22823ExceptionHandler.call @ angular2.js:1166(anonymous function) @ angular2.js:12481NgZone._notifyOnError @ angular2.js:13405collection_1.StringMapWrapper.merge.onError @ angular2.js:13309run @ angular2-polyfills.js:141(anonymous function) @ angular2.js:13328zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:1511lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:1523lib$es6$promise$$internal$$publish @ angular2-polyfills.js:1494(anonymous function) @ angular2-polyfills.js:243microtask @ angular2.js:13360run @ angular2-polyfills.js:138(anonymous function) @ angular2.js:13328zoneBoundFn @ angular2-polyfills.js:111lib$es6$promise$asap$$flush @ angular2-polyfills.js:1305`

**Comment by chenkie** [comment]
Hey @kieranfraser, a couple questions :)

* How come you're moving `angular2-jwt.js` out of the `node_modules` folder? Is it just for experimenting? Ideally you'd want to keep it in `node_modules`.
* Does your app boot properly when you don't try to use `angular2-jwt`? From your stack trace it looks like there might be other issues at play, since no selector is being found.

**Comment by kieranfraser** [comment]
Thanks for the reply! So I'm moving `angular2-jwt.js` out of the `node_modules` folder and into a public folder because I don't want to expose the `node_modules` folder on the client side. I've read this is best practice? 

The app did boot properly. The error I mentioned above is now fixed, it was a syntax error on the selector tag (very basic mistake haha).

But now I've got a new error that I believe was mentioned in issue #36
"Uncaught ReferenceError: require is not defined" 
This points to an error in angular-jwt.js on line 10 -> `var core_1 = require('angular2/core');`

It also errors on:
"Uncaught TypeError: Cannot read property 'split' of undefined"

I did get this app running without any errors, however when deploying to azure it broke and then I noticed my npm version was quite old compared to the one being used in azure. When I updated to version 3.6.0 and ran npm install and tried to rerun my application locally it was broken with the errors above (just as in azure). Any ideas why this is so? I feel like it's the dependency versions that are causing this error?

**Comment by escardin** [comment]
@kieranfraser for development, having stuff in node_modules is fine. For prod, you would use something like webpack, browserify, jspm or system-builder (likely system builder in your case) to manage getting the proper libs into your redistributable.

**Comment by kieranfraser** [comment]
@escardin thanks for confirming, and yes I'm using system-builder! 
Also, quick update (which is more confusing to me):

The application is now working having reverted to the "old" angular2-jwt.js file generated with my older version of npm. I copied the angular2-jwt.js folder from the old generation to the node_modules folder and everything worked perfectly. 
Then on comparing the two versions of angular2-jwt (version generated with old npm version vs that generated with version 3.6.0) I see that they are very different and that the "old" one doesn't contain the "require" line, hence there's no error and the app runs. Why would the files be different? and why is the "old" one working and the "new" one not working?

**Comment by escardin** [comment]
Ah, several versions ago the library was packaged for system users only, and was breaking for everyone else. It's now compiled into common js format and you need to add a mapping for the lib in your system.config, basically like how you have in your initial description.

**Comment by chenkie** [comment]
Hows it going now @kieranfraser ?

**Comment by corlnethank** [comment]
A quick and simple rebuild of the source fixed it up for me just fine, I also did a refresh on the ref node packages as well.
