### ISSUE TITLE
v5.1.0 broke azure devops publishing

### ISSUE THREAD

**Issue by MarkStevens75** [auth0/angular2-jwt#743]
Deploy was failing on Azure devops due to the following issues, reverted to previous version and issues were resolved.

EXEC : error : node_modules/@auth0/angular-jwt/lib/angular-jwt.module.d.ts:20:21 - error TS2694: Namespace '"C:/agent/_work/2/s/WebApp/ClientApp/node_modules/@angular/core/core"' has no exported member '╔╡╔╡FactoryDeclaration'. [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  
  20     static ╔╡fac: i0.╔╡╔╡FactoryDeclaration<JwtModule, [{ optional: true; skipSelf: true; }]>;
                         ~~~~~~~~~~~~~~~~~~~~
  
  
EXEC : error : node_modules/@auth0/angular-jwt/lib/angular-jwt.module.d.ts:21:21 - error TS2694: Namespace '"C:/agent/_work/2/s/WebApp/ClientApp/node_modules/@angular/core/core"' has no exported member '╔╡╔╡NgModuleDeclaration'. [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  
  21     static ╔╡mod: i0.╔╡╔╡NgModuleDeclaration<JwtModule, never, never, never>;
                         ~~~~~~~~~~~~~~~~~~~~~
  
  
EXEC : error : node_modules/@auth0/angular-jwt/lib/angular-jwt.module.d.ts:22:21 - error TS2694: Namespace '"C:/agent/_work/2/s/WebApp/ClientApp/node_modules/@angular/core/core"' has no exported member '╔╡╔╡InjectorDeclaration'. [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  
  22     static ╔╡inj: i0.╔╡╔╡InjectorDeclaration<JwtModule>;
                         ~~~~~~~~~~~~~~~~~~~~~
  
  
EXEC : error : node_modules/@auth0/angular-jwt/lib/jwt.interceptor.d.ts:21:21 - error TS2694: Namespace '"C:/agent/_work/2/s/WebApp/ClientApp/node_modules/@angular/core/core"' has no exported member '╔╡╔╡FactoryDeclaration'. [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  
  21     static ╔╡fac: i0.╔╡╔╡FactoryDeclaration<JwtInterceptor, never>;
                         ~~~~~~~~~~~~~~~~~~~~
  
  
EXEC : error : node_modules/@auth0/angular-jwt/lib/jwt.interceptor.d.ts:22:22 - error TS2694: Namespace '"C:/agent/_work/2/s/WebApp/ClientApp/node_modules/@angular/core/core"' has no exported member '╔╡╔╡InjectableDeclaration'. [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  
  22     static ╔╡prov: i0.╔╡╔╡InjectableDeclaration<JwtInterceptor>;
                          ~~~~~~~~~~~~~~~~~~~~~~~
  
  
EXEC : error : node_modules/@auth0/angular-jwt/lib/jwthelper.service.d.ts:13:21 - error TS2694: Namespace '"C:/agent/_work/2/s/WebApp/ClientApp/node_modules/@angular/core/core"' has no exported member '╔╡╔╡FactoryDeclaration'. [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  
  13     static ╔╡fac: i0.╔╡╔╡FactoryDeclaration<JwtHelperService, never>;
                         ~~~~~~~~~~~~~~~~~~~~
  
  
EXEC : error : node_modules/@auth0/angular-jwt/lib/jwthelper.service.d.ts:14:22 - error TS2694: Namespace '"C:/agent/_work/2/s/WebApp/ClientApp/node_modules/@angular/core/core"' has no exported member '╔╡╔╡InjectableDeclaration'. [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  
  14     static ╔╡prov: i0.╔╡╔╡InjectableDeclaration<JwtHelperService>;
  
  

EXEC : error : ./node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.js 244:21-42 [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  "export '╔╡╔╡ngDeclareFactory' (imported as 'i0') was not found in '@angular/core'
      at HarmonyImportSpecifierDependency._getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
      at HarmonyImportSpecifierDependency.getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
      at Compilation.reportDependencyErrorsAndWarnings (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1463:22)
      at C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
      at _next0 (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
      at eval (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:55:1)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
   @ ./src/app/app.module.ts
   @ ./src/main.ts
   @ multi ./src/main.ts
  
EXEC : error : ./node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.js 109:29-53 [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  "export '╔╡╔╡ngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'
      at HarmonyImportSpecifierDependency._getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
      at HarmonyImportSpecifierDependency.getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
      at Compilation.reportDependencyErrorsAndWarnings (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1463:22)
      at C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
      at _next0 (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
      at eval (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:55:1)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
   @ ./src/app/app.module.ts
   @ ./src/main.ts
   @ multi ./src/main.ts
  
EXEC : error : ./node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.js 205:27-51 [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  "export '╔╡╔╡ngDeclareInjectable' (imported as 'i0') was not found in '@angular/core'
      at HarmonyImportSpecifierDependency._getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
      at HarmonyImportSpecifierDependency.getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
      at Compilation.reportDependencyErrorsAndWarnings (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1463:22)
      at C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
      at _next0 (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
      at eval (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:55:1)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
   @ ./src/app/app.module.ts
   @ ./src/main.ts
   @ multi ./src/main.ts
  
EXEC : error : ./node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.js 246:21-43 [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  "export '╔╡╔╡ngDeclareInjector' (imported as 'i0') was not found in '@angular/core'
      at HarmonyImportSpecifierDependency._getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
      at HarmonyImportSpecifierDependency.getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
      at Compilation.reportDependencyErrorsAndWarnings (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1463:22)
      at C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
      at _next0 (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
      at eval (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:55:1)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
   @ ./src/app/app.module.ts
   @ ./src/main.ts
   @ multi ./src/main.ts
  
EXEC : error : ./node_modules/@auth0/angular-jwt/fesm2015/auth0-angular-jwt.js 245:21-43 [C:\agent\_work\2\s\WebApp\WebApp.csproj]
  "export '╔╡╔╡ngDeclareNgModule' (imported as 'i0') was not found in '@angular/core'
      at HarmonyImportSpecifierDependency._getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
      at HarmonyImportSpecifierDependency.getErrors (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
      at Compilation.reportDependencyErrorsAndWarnings (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1463:22)
      at C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
      at _next0 (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:41:1)
      at eval (eval at create (C:\agent\_work\2\s\WebApp\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:55:1)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
   @ ./src/app/app.module.ts
   @ ./src/main.ts
   @ multi ./src/main.ts

  
  
                          ~~~~~~~~~~~~~~~~~~~~~~~

**Comment by MarkStevens75** [comment]
dotnet publish --configuration release --output $(build.artifactstagingdirectory)

**Comment by frederikprijck** [comment]
Angular 11 is no longer supported by Google, see https://angular.io/guide/releases#actively-supported-versions.

You should be fine pinning your version of our SDK down to 5.0.x, but we would recommend using Angular 12+.
