### ISSUE TITLE
No provider for AuthConfig!

### ISSUE THREAD

**Issue by keerthivasan-r** [auth0/angular2-jwt#88]
Hi,

I have passed AuthConfig object to AuthHttp while bootstrapping the app component. Now, i would like to inject it my component service. How can i do that?

```
bootstrap(App, [
  HTTP_PROVIDERS,
  provide(AuthHttp, {
    useFactory: (http) => {
      return new AuthHttp(new AuthConfig({
        headerName: YOUR_HEADER_NAME,
        headerPrefix: YOUR_HEADER_PREFIX,
        tokenName: YOUR_TOKEN_NAME,
        tokenGetter: YOUR_TOKEN_GETTER_FUNCTION,
        globalHeaders: [{'Content-Type':'application/json'}],
        noJwtError: true,
        noTokenScheme: true
      }), http);
    },
    deps: [Http]
  })
])
```
I'm getting the following error

```
ORIGINAL EXCEPTION: No provider for AuthConfig!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:3000/vendor.bundle.js:1079:24)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:3000/vendor.bundle.js:9964:17)
```

I have also included it in the app component providers as well.

```
@Component({
  selector: 'app',
  pipes: [ ],
  providers: [ROUTER_PROVIDERS,MockLoginResponse,LoginService,AuthHttp,
  MockRegistrationResponse,RegistrationService
  ,ForgotPwdService,MockForgotPwdResponse],
  directives: [ROUTER_DIRECTIVES,LoginComponent],
  encapsulation: ViewEncapsulation.None,
  template: `<router-outlet></router-outlet>`
})
```

Can someone help?

**Comment by escardin** [comment]
You're not supposed to provide AuthHttp multiple times. That providers section on your component is trying to make a NEW AuthHttp.

You should read the following docs:
https://angular.io/docs/ts/latest/guide/dependency-injection.html
https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html
